apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eahycaf3y-nodejs 
  janus-idp.io/tekton: eahycaf3y-nodejs
  backstage.io/kubernetes-id: eahycaf3y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eahycaf3y-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  